Add good scrollbar for standings.html
Algocode-CMS/algocode pull request #6
Opened 2020-11-12 15:17 UTC by developerxyzw

Works in modern Chrome and Firefox

2020-11-12 18:04 UTC, grphil requested changes
У меня локально вообще никаких изменений нет, всё равно скролбар есть только если домотать до низу, и там часто он покрывается столбцами с именим, из-за не всегда получается легко им пользоваться

2020-11-12 18:04 UTC, grphil commented on courses/templates/standings.html
> +<body style="table#standings_fixed { position: fixed; } div.wrapper { width: fit-content; width: -moz-fit-content; overflow-x: hidden; }">
Это надо в static/standings.css добавить

2020-11-12 18:04 UTC, grphil commented on courses/templates/standings.html
> +<script>
Это надо в static/standings.js добавить

2020-11-13 10:02 UTC, developerxyzw commented
Moved scripts and styles to corresponding files

2024-02-26 21:59 UTC, closed without merging